### ISSUE TITLE
KWIs must be 'queryable'

### ISSUE THREAD

**Issue by ont-app** [ont-app/igraph#5]
Some native representations, (notably RDF) may have nodes (in the case of RDF, notably blank nodes) in the graph that are not 'queryable'. In the case of blank nodes, the identifying information of a blank node is only valid in the scope of the query that retrieved the node. It is therefore non-trivial to mint a URI for such a node which is suitable for use as say, a subject in an IGraph.

Solutions to this problem are probably platform-specific, but we should recognize errors of this kind, and document this constraint.

Done when:
- There is an error type defined identifying query failures of this kind, with a helpful explanation.
- Documentation explains this constraint.

**Comment by ericdscott** [comment]
Actually at this level we don't have opinions about KWIs yet (any
hashable value should be able to serve as a node). Moving this [igraph-vocabulary](https://github.com/ont-app/igraph-vocabulary/issues/2)
